#!/bin/bash
set -e

# ============================================================================
#                     AQUATEMP QUICK LAUNCH SCRIPT
# ============================================================================
# Generated by spec-init on 2025-10-05
# Spec-Kit Version: 2.0.0
# Project Type: Home Assistant Integration + Next.js Dashboard
# ============================================================================

# Color definitions
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly MAGENTA='\033[0;35m'
readonly WHITE='\033[1;37m'
readonly NC='\033[0m' # No Color
readonly BOLD='\033[1m'

# Project configuration
PROJECT_NAME="AquaTemp"
PROJECT_TYPE="Python/TypeScript"
FRAMEWORK="Home Assistant + Next.js"
VERSION="3.1.0"
SERVICES="InfluxDB, Grafana"
PROXMOX_NODE="${PROXMOX_NODE:-proxmox-01}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3000}"
INFLUX_URL="${INFLUX_URL:-http://10.31.222.5:8086}"

# Print beautiful header
print_header() {
    clear
    echo -e "${CYAN}${BOLD}"
    echo "╔════════════════════════════════════════════════════════════════════════════════════╗"
    echo "║                          AQUATEMP PLATFORM v${VERSION}                              ║"
    echo "║                    Home Assistant Heat Pump Integration                             ║"
    echo "╠════════════════════════════════════════════════════════════════════════════════════╣"
    printf "║ ${WHITE}Tech Stack:${NC}${CYAN} %-18s ${WHITE}Framework:${NC}${CYAN} %-30s ║\n" "$PROJECT_TYPE" "$FRAMEWORK"
    printf "║ ${WHITE}Version:${NC}${CYAN} %-22s ${WHITE}Services:${NC}${CYAN} %-30s ║\n" "$VERSION" "$SERVICES"
    printf "║ ${WHITE}Dashboard:${NC}${CYAN} %-20s ${WHITE}InfluxDB:${NC}${CYAN} %-30s ║\n" "localhost:$DASHBOARD_PORT" "$INFLUX_URL"
    echo "╚════════════════════════════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Show menu options
show_menu() {
    echo -e "${BOLD}Select an option:${NC}"
    echo ""
    echo -e "${GREEN}Dashboard & Development:${NC}"
    echo "  1. 🚀 Run Dashboard Development Server"
    echo "  2. 🛠️  Build Dashboard for Production"
    echo ""
    echo -e "${BLUE}Home Assistant Integration:${NC}"
    echo "  3. 📦 Build Integration Package (ZIP)"
    echo "  4. 🔄 Copy Integration to HA (local)"
    echo "  5. 🐳 Deploy to Home Assistant (Docker)"
    echo ""
    echo -e "${MAGENTA}Testing & Quality:${NC}"
    echo "  6. 🧪 Run All Tests"
    echo "  7. 🔬 Run Admin Tests"
    echo "  8. 📊 Run Tests with Coverage"
    echo "  9. 👀 Run Tests (Watch Mode)"
    echo "  10. 🔍 Lint & Format Code"
    echo ""
    echo -e "${YELLOW}Monitoring & Data:${NC}"
    echo "  11. 📊 Check InfluxDB Status"
    echo "  12. 📈 Open Grafana Dashboard"
    echo ""
    echo -e "${WHITE}Management:${NC}"
    echo "  13. 🔧 Install/Update Dependencies"
    echo "  14. 🧹 Clean Project"
    echo "  15. 📚 Generate Documentation"
    echo ""
    echo -e "${CYAN}Admin Features:${NC}"
    echo "  16. 🔐 Setup Admin Credentials"
    echo "  17. 🌐 Open Admin Dashboard"
    echo ""
    echo "  18. ❓ Help & Information"
    echo ""
    echo "  q. 🚪 Exit"
    echo ""
}

# Run dashboard development server
run_dashboard_dev() {
    echo -e "${GREEN}Starting Next.js dashboard development server...${NC}"
    cd pool-dashboard

    # Check if .env.local exists
    if [ ! -f .env.local ]; then
        echo -e "${YELLOW}Creating .env.local from .env.example...${NC}"
        cp .env.example .env.local
        echo -e "${YELLOW}Please update .env.local with your InfluxDB credentials${NC}"
        read -p "Press Enter after updating .env.local..."
    fi

    npm run dev
    cd ..
}

# Build dashboard for production
build_dashboard() {
    echo -e "${GREEN}Building Next.js dashboard for production...${NC}"
    cd pool-dashboard
    npm run build
    echo -e "${GREEN}Build complete! Run with: npm start${NC}"
    cd ..
}

# Build integration package
build_integration() {
    echo -e "${GREEN}Building AquaTemp integration package...${NC}"

    # Update version
    read -p "Enter new version (current: $VERSION): " new_version
    if [ ! -z "$new_version" ]; then
        VERSION=$new_version
        # Update version in manifest.json
        sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/aqua_temp/manifest.json
    fi

    # Create ZIP package
    zip_name="aqua_temp_v${VERSION}.zip"
    echo -e "${CYAN}Creating ${zip_name}...${NC}"

    cd custom_components
    zip -r "../${zip_name}" aqua_temp/ -x "*.pyc" -x "*__pycache__*"
    cd ..

    echo -e "${GREEN}✅ Package created: ${zip_name}${NC}"
}

# Copy integration to Home Assistant
copy_to_ha() {
    echo -e "${GREEN}Copying integration to Home Assistant...${NC}"

    read -p "Enter HA config directory path [/config]: " ha_path
    ha_path="${ha_path:-/config}"

    if [ -d "$ha_path/custom_components" ]; then
        cp -r custom_components/aqua_temp "$ha_path/custom_components/"
        echo -e "${GREEN}✅ Integration copied to $ha_path/custom_components/aqua_temp${NC}"
        echo -e "${YELLOW}Restart Home Assistant to load the integration${NC}"
    else
        echo -e "${RED}Error: $ha_path/custom_components not found${NC}"
    fi
}

# Deploy to Home Assistant Docker
deploy_to_ha_docker() {
    echo -e "${GREEN}Deploying to Home Assistant Docker...${NC}"

    read -p "Enter HA container name [homeassistant]: " container_name
    container_name="${container_name:-homeassistant}"

    # Copy to container
    docker cp custom_components/aqua_temp "${container_name}:/config/custom_components/"

    # Restart container
    echo -e "${YELLOW}Restarting Home Assistant container...${NC}"
    docker restart "$container_name"

    echo -e "${GREEN}✅ Deployment complete!${NC}"
}

# Run test suite
run_tests() {
    echo -e "${GREEN}Running test suite...${NC}"

    # Python tests
    if [ -d "tests" ] && command -v python3 &> /dev/null; then
        echo -e "${CYAN}Running Python tests...${NC}"
        python -m pytest tests/ -v 2>/dev/null || echo "No Python tests found or pytest not installed"
    fi

    # Dashboard tests (JavaScript/TypeScript)
    if [ -f "pool-dashboard/package.json" ]; then
        echo -e "${CYAN}Running Dashboard tests...${NC}"
        cd pool-dashboard

        # Check if tests are configured
        if grep -q "\"test\":" package.json; then
            npm test -- --run
            echo -e "${GREEN}✅ Dashboard tests complete${NC}"
        else
            echo -e "${YELLOW}No tests configured for dashboard${NC}"
        fi
        cd ..
    fi
}

# Run admin tests specifically
run_admin_tests() {
    echo -e "${GREEN}Running Admin System tests...${NC}"
    cd pool-dashboard

    if [ ! -f "package.json" ]; then
        echo -e "${RED}Error: Not in dashboard directory${NC}"
        cd ..
        return 1
    fi

    # Check if vitest is installed
    if ! grep -q "vitest" package.json; then
        echo -e "${YELLOW}Installing test dependencies...${NC}"
        npm install -D vitest @testing-library/react @testing-library/jest-dom @vitejs/plugin-react jsdom
    fi

    echo -e "${CYAN}Running Admin tests with Vitest...${NC}"
    npm test -- --run

    echo ""
    echo -e "${CYAN}Test Summary:${NC}"
    echo "  • Authentication tests (login, logout, sessions)"
    echo "  • Settings CRUD tests (save, load, reset)"
    echo "  • Tariff configuration tests (time calculations)"
    echo "  • Report export tests (PDF, CSV, Excel)"

    cd ..
}

# Run tests with coverage
run_tests_coverage() {
    echo -e "${GREEN}Running tests with coverage...${NC}"
    cd pool-dashboard

    if [ ! -f "package.json" ]; then
        echo -e "${RED}Error: Not in dashboard directory${NC}"
        cd ..
        return 1
    fi

    echo -e "${CYAN}Running tests with coverage report...${NC}"
    npm run test:coverage 2>/dev/null || npm test -- --run --coverage

    echo -e "${GREEN}✅ Coverage report generated${NC}"
    echo -e "${YELLOW}Check pool-dashboard/coverage/ for detailed report${NC}"

    cd ..
}

# Run tests in watch mode
run_tests_watch() {
    echo -e "${GREEN}Starting test watcher...${NC}"
    cd pool-dashboard

    if [ ! -f "package.json" ]; then
        echo -e "${RED}Error: Not in dashboard directory${NC}"
        cd ..
        return 1
    fi

    echo -e "${CYAN}Starting Vitest in watch mode...${NC}"
    echo -e "${YELLOW}Press 'q' to quit, 'a' to run all tests${NC}"
    npm test

    cd ..
}

# Lint and format code
lint_code() {
    echo -e "${GREEN}Running linters and formatters...${NC}"

    # Python
    echo -e "${CYAN}Python linting with flake8...${NC}"
    flake8 custom_components/aqua_temp/ --max-line-length=120 || true

    echo -e "${CYAN}Python formatting with black...${NC}"
    black custom_components/aqua_temp/ || true

    # JavaScript/TypeScript
    if [ -d "pool-dashboard" ]; then
        echo -e "${CYAN}Dashboard linting...${NC}"
        cd pool-dashboard
        npm run lint || true
        cd ..
    fi
}

# Check InfluxDB status
check_influxdb() {
    echo -e "${GREEN}Checking InfluxDB connection...${NC}"

    if command -v python3 &> /dev/null; then
        python3 check_influxdb.py 2>/dev/null || {
            echo -e "${YELLOW}check_influxdb.py not found or failed${NC}"
            echo -e "${CYAN}Testing connection to $INFLUX_URL...${NC}"
            curl -s "$INFLUX_URL/ping" && echo -e "${GREEN}✅ InfluxDB is accessible${NC}" || echo -e "${RED}❌ Cannot reach InfluxDB${NC}"
        }
    fi
}

# Open Grafana dashboard
open_grafana() {
    echo -e "${GREEN}Opening Grafana dashboard...${NC}"

    grafana_url="http://10.31.222.5:3001"
    echo -e "${CYAN}Grafana URL: $grafana_url${NC}"

    # Try to open in browser
    if command -v open &> /dev/null; then
        open "$grafana_url"
    elif command -v xdg-open &> /dev/null; then
        xdg-open "$grafana_url"
    else
        echo -e "${YELLOW}Please open in browser: $grafana_url${NC}"
    fi
}

# Install/Update dependencies
install_deps() {
    echo -e "${GREEN}Installing/Updating dependencies...${NC}"

    # Python dependencies
    echo -e "${CYAN}Installing Python dependencies...${NC}"
    pip install -r requirements.txt

    # Dashboard dependencies
    if [ -d "pool-dashboard" ]; then
        echo -e "${CYAN}Installing Dashboard dependencies...${NC}"
        cd pool-dashboard
        npm install
        cd ..
    fi

    echo -e "${GREEN}✅ Dependencies installed${NC}"
}

# Clean project
clean_project() {
    echo -e "${GREEN}Cleaning project...${NC}"

    # Remove Python cache
    find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find . -type f -name "*.pyc" -delete 2>/dev/null || true

    # Clean Next.js build
    if [ -d "pool-dashboard/.next" ]; then
        echo -e "${CYAN}Cleaning Next.js build...${NC}"
        rm -rf pool-dashboard/.next
    fi

    # Clean test cache
    rm -rf .pytest_cache 2>/dev/null || true

    echo -e "${GREEN}✅ Project cleaned${NC}"
}

# Generate documentation
generate_docs() {
    echo -e "${GREEN}Generating documentation...${NC}"

    # Create docs directory
    mkdir -p docs

    # Generate README sections
    cat > docs/ARCHITECTURE.md << 'EOF'
# AquaTemp Architecture

## Overview
AquaTemp is a Home Assistant integration for Aqua Temp heat pump pool heaters with a modern Next.js monitoring dashboard.

## Components

### Home Assistant Integration
- Location: `custom_components/aqua_temp/`
- Purpose: Interface with Aqua Temp API and expose sensors to HA
- Key Features:
  - Real-time temperature monitoring
  - Power consumption tracking
  - Mode control (heating/cooling/auto)
  - Error detection and diagnostics

### Monitoring Dashboard
- Location: `pool-dashboard/`
- Technology: Next.js 15 with TypeScript
- Features:
  - Real-time metrics from InfluxDB
  - Historical data visualization
  - Responsive design
  - Dark mode support

### Data Pipeline
1. Heat Pump → Aqua Temp Cloud API
2. Home Assistant Integration → Polls API
3. HA → Writes to InfluxDB
4. Dashboard → Queries InfluxDB
5. Grafana → Advanced visualizations

## Deployment
- Home Assistant: Docker or Core installation
- Dashboard: Node.js server or Docker
- Monitoring: InfluxDB + Grafana stack
EOF

    echo -e "${GREEN}✅ Documentation generated in docs/${NC}"
}

# Setup admin credentials
setup_admin_credentials() {
    echo -e "${GREEN}Setting up admin credentials...${NC}"
    cd pool-dashboard

    if [ ! -f .env.local ]; then
        cp .env.example .env.local
    fi

    echo ""
    echo -e "${CYAN}Configure admin access:${NC}"
    read -p "Enter admin username [admin]: " admin_user
    admin_user="${admin_user:-admin}"

    read -sp "Enter admin password: " admin_pass
    echo ""

    # Generate a random auth secret if not exists
    auth_secret=$(openssl rand -base64 32 2>/dev/null || echo "change-this-to-a-random-secret-$(date +%s)")

    # Update .env.local
    if grep -q "AUTH_SECRET=" .env.local; then
        sed -i.bak "s|^AUTH_SECRET=.*|AUTH_SECRET=$auth_secret|" .env.local
    else
        echo "AUTH_SECRET=$auth_secret" >> .env.local
    fi

    if grep -q "ADMIN_USERNAME=" .env.local; then
        sed -i.bak "s|^ADMIN_USERNAME=.*|ADMIN_USERNAME=$admin_user|" .env.local
    else
        echo "ADMIN_USERNAME=$admin_user" >> .env.local
    fi

    if grep -q "ADMIN_PASSWORD=" .env.local; then
        sed -i.bak "s|^ADMIN_PASSWORD=.*|ADMIN_PASSWORD=$admin_pass|" .env.local
    else
        echo "ADMIN_PASSWORD=$admin_pass" >> .env.local
    fi

    echo -e "${GREEN}✅ Admin credentials configured in pool-dashboard/.env.local${NC}"
    echo -e "${YELLOW}Keep your credentials secure and don't commit .env.local to git${NC}"

    cd ..
}

# Open admin dashboard
open_admin_dashboard() {
    echo -e "${GREEN}Opening admin dashboard...${NC}"

    # Check which port the dashboard is actually running on
    if lsof -i:3000 &>/dev/null; then
        actual_port=3000
    elif lsof -i:3002 &>/dev/null; then
        actual_port=3002
    elif lsof -i:3001 &>/dev/null; then
        actual_port=3001
    else
        actual_port=${DASHBOARD_PORT}
        echo -e "${YELLOW}Dashboard may not be running. Starting on default port ${actual_port}...${NC}"
        echo -e "${YELLOW}Please run option 1 first to start the dashboard.${NC}"
    fi

    admin_url="http://localhost:${actual_port}/admin"
    echo -e "${CYAN}Admin URL: $admin_url${NC}"
    echo -e "${CYAN}Login credentials:${NC}"
    echo -e "  Username: ${GREEN}admin${NC}"
    echo -e "  Password: ${GREEN}(check your .env.local file)${NC}"

    # Try to open in browser
    if command -v open &> /dev/null; then
        open "$admin_url"
        echo -e "${GREEN}✅ Opened admin dashboard in browser${NC}"
    elif command -v xdg-open &> /dev/null; then
        xdg-open "$admin_url"
        echo -e "${GREEN}✅ Opened admin dashboard in browser${NC}"
    else
        echo -e "${YELLOW}Please open in browser: $admin_url${NC}"
    fi
}

# Show help
show_help() {
    echo -e "${BOLD}${CYAN}AquaTemp Platform Help${NC}"
    echo ""
    echo -e "${WHITE}Project Structure:${NC}"
    echo "  custom_components/aqua_temp/ - Home Assistant integration"
    echo "  pool-dashboard/              - Next.js monitoring dashboard"
    echo "  tests/                       - Test suite"
    echo "  specs/                       - Feature specifications"
    echo ""
    echo -e "${WHITE}Quick Start:${NC}"
    echo "  1. Install dependencies (option 13)"
    echo "  2. Configure .env.local in pool-dashboard/"
    echo "  3. Setup admin credentials (option 16)"
    echo "  4. Run dashboard dev server (option 1)"
    echo "  5. Access admin at /admin (option 17)"
    echo "  6. Run admin tests (option 7)"
    echo ""
    echo -e "${WHITE}Environment Variables:${NC}"
    echo "  DASHBOARD_PORT - Dashboard port (default: 3000)"
    echo "  INFLUX_URL     - InfluxDB URL (default: http://10.31.222.5:8086)"
    echo "  PROXMOX_NODE   - Proxmox deployment node"
    echo "  ADMIN_USERNAME - Admin login username"
    echo "  ADMIN_PASSWORD - Admin login password"
    echo ""
    echo -e "${WHITE}Admin Features:${NC}"
    echo "  • Settings management (pool config, thresholds)"
    echo "  • Tariff configuration (electricity pricing)"
    echo "  • Report generation (PDF, CSV, Excel exports)"
    echo ""
    echo -e "${WHITE}Version:${NC} $VERSION"
    echo -e "${WHITE}Documentation:${NC} https://github.com/radical-squared/aquatemp"
}

# Main execution loop
main() {
    while true; do
        print_header
        show_menu
        read -rp "Your choice: " choice

        case $choice in
            1) run_dashboard_dev ;;
            2) build_dashboard ;;
            3) build_integration ;;
            4) copy_to_ha ;;
            5) deploy_to_ha_docker ;;
            6) run_tests ;;
            7) run_admin_tests ;;
            8) run_tests_coverage ;;
            9) run_tests_watch ;;
            10) lint_code ;;
            11) check_influxdb ;;
            12) open_grafana ;;
            13) install_deps ;;
            14) clean_project ;;
            15) generate_docs ;;
            16) setup_admin_credentials ;;
            17) open_admin_dashboard ;;
            18) show_help ;;
            q|Q) echo -e "${GREEN}👋 Goodbye!${NC}"; exit 0 ;;
            *) echo -e "${RED}Invalid option. Please try again.${NC}" ;;
        esac

        echo ""
        read -rp "Press Enter to continue..."
    done
}

# Check for command line arguments
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    show_help
    exit 0
fi

# Run main function
main "$@"