#!/usr/bin/env bash
##############################################
# Pool Dashboard - Proxmox Deployment Script
# Target: 192.168.0.202
# Auto-generated by spec-kit deployment
##############################################

set -euo pipefail

# Configuration
PROXMOX_HOST="192.168.0.202"
PROXMOX_USER="${PROXMOX_USER:-root}"
CONTAINER_ID="${CONTAINER_ID:-200}"
PROJECT_NAME="pool-dashboard"
IMAGE_FILE="/tmp/pool-dashboard.tar.gz"
PORT="${PORT:-3000}"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}ℹ ${NC}$1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if image file exists
if [[ ! -f "${IMAGE_FILE}" ]]; then
    log_error "Docker image not found at ${IMAGE_FILE}"
    log_info "Run: docker save pool-dashboard:latest | gzip > ${IMAGE_FILE}"
    exit 1
fi

log_info "Starting deployment to Proxmox ${PROXMOX_HOST}..."

# Step 1: Transfer Docker image to Proxmox host
log_info "Transferring Docker image (92MB)..."
scp "${IMAGE_FILE}" "${PROXMOX_USER}@${PROXMOX_HOST}:/tmp/" || {
    log_error "Failed to transfer image"
    exit 1
}
log_success "Image transferred"

# Step 2: Execute deployment on Proxmox
log_info "Executing deployment on Proxmox..."

ssh "${PROXMOX_USER}@${PROXMOX_HOST}" <<'REMOTE_SCRIPT'
set -euo pipefail

# Load environment variables
CONTAINER_ID=200
PROJECT_NAME="pool-dashboard"
IMAGE_FILE="/tmp/pool-dashboard.tar.gz"
PORT=3000

echo "→ Checking if container ${CONTAINER_ID} exists..."
if pct status ${CONTAINER_ID} 2>/dev/null; then
    echo "  Container ${CONTAINER_ID} exists, stopping..."
    pct stop ${CONTAINER_ID} || true
    sleep 2
else
    echo "  Creating new LXC container ${CONTAINER_ID}..."

    # Create Ubuntu container with Docker support
    pct create ${CONTAINER_ID} \
        local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.gz \
        --hostname ${PROJECT_NAME} \
        --memory 4096 \
        --cores 4 \
        --swap 1024 \
        --storage local-lvm \
        --rootfs local-lvm:16 \
        --net0 name=eth0,bridge=vmbr0,ip=dhcp,firewall=1 \
        --unprivileged 1 \
        --features nesting=1,keyctl=1 \
        --ostype ubuntu || {
        echo "ERROR: Failed to create container"
        exit 1
    }
fi

echo "→ Starting container..."
pct start ${CONTAINER_ID}
sleep 5

echo "→ Installing Docker and dependencies..."
pct exec ${CONTAINER_ID} -- bash -c "
    export DEBIAN_FRONTEND=noninteractive

    # Update and install prerequisites
    apt-get update
    apt-get install -y ca-certificates curl gnupg

    # Add Docker's official GPG key
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repository
    echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo \$VERSION_CODENAME) stable\" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Install Docker
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    # Enable and start Docker
    systemctl enable docker
    systemctl start docker

    echo '✓ Docker installed successfully'
"

echo "→ Transferring Docker image to container..."
pct push ${CONTAINER_ID} ${IMAGE_FILE} /tmp/pool-dashboard.tar.gz

echo "→ Loading Docker image..."
pct exec ${CONTAINER_ID} -- bash -c "
    docker load < /tmp/pool-dashboard.tar.gz
    rm /tmp/pool-dashboard.tar.gz
"

echo "→ Stopping existing pool-dashboard container (if any)..."
pct exec ${CONTAINER_ID} -- bash -c "
    docker stop ${PROJECT_NAME} 2>/dev/null || true
    docker rm ${PROJECT_NAME} 2>/dev/null || true
"

echo "→ Starting pool-dashboard application..."
pct exec ${CONTAINER_ID} -- bash -c "
    docker run -d \
        --name ${PROJECT_NAME} \
        --restart unless-stopped \
        -p ${PORT}:3000 \
        -e NODE_ENV=production \
        -e HOSTNAME=0.0.0.0 \
        -e NEXTAUTH_URL=http://192.168.0.129:3000 \
        -e AUTH_TRUST_HOST=true \
        -e NEXTAUTH_SECRET=pool-dashboard-secret-key-change-in-production \
        -e GRAFANA_URL=http://192.168.0.6:3000 \
        -e NEXT_PUBLIC_GRAFANA_DASHBOARD_UID_ALOHA=f0d68b75-8119-4ca3-b749-dfa9d8f116b3 \
        -e NEXT_PUBLIC_GRAFANA_DASHBOARD_UID_GENERAL=88495143-b01e-484a-9a04-3ef230fa5d25 \
        --health-cmd='wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1' \
        --health-interval=30s \
        --health-retries=3 \
        --health-start-period=40s \
        --health-timeout=10s \
        pool-dashboard:latest
"

echo "→ Configuring firewall..."
pct exec ${CONTAINER_ID} -- bash -c "
    apt-get install -y ufw
    ufw allow ${PORT}/tcp
    ufw allow 22/tcp
    ufw --force enable
" 2>/dev/null || echo "  UFW configuration skipped (optional)"

echo ""
echo "========================================="
echo "✓ Deployment Complete!"
echo "========================================="
echo ""
echo "Container ID: ${CONTAINER_ID}"
echo "Application: ${PROJECT_NAME}"
echo "Port: ${PORT}"
echo ""

# Get container IP
CONTAINER_IP=\$(pct exec ${CONTAINER_ID} -- bash -c "hostname -I | awk '{print \$1}'")
echo "Access URL: http://\${CONTAINER_IP}:${PORT}"
echo "Proxmox Host: http://$(hostname -I | awk '{print $1}')"
echo ""
echo "Container Status:"
pct exec ${CONTAINER_ID} -- docker ps --filter name=${PROJECT_NAME}
echo ""

REMOTE_SCRIPT

log_success "Deployment completed successfully!"
log_info ""
log_info "Next steps:"
log_info "  1. Access the dashboard at: http://192.168.0.202:3000"
log_info "  2. Check container health: ssh ${PROXMOX_USER}@${PROXMOX_HOST} 'pct exec ${CONTAINER_ID} -- docker ps'"
log_info "  3. View logs: ssh ${PROXMOX_USER}@${PROXMOX_HOST} 'pct exec ${CONTAINER_ID} -- docker logs ${PROJECT_NAME}'"
log_info ""
